artifact_location: file:///C:/Users/jnama/machine/Students-grade-prediction-model/your_mlflow_uri/871227263369960388
creation_time: 1711026061539
experiment_id: '871227263369960388'
last_update_time: 1711026061539
lifecycle_stage: active
name: your_experiment_name
