artifact_location: file:///C:/Users/jnama/machine/Students-grade-prediction-model/your_mlflow_uri/0
creation_time: 1711026061518
experiment_id: '0'
last_update_time: 1711026061518
lifecycle_stage: active
name: Default
