artifact_uri: file:///C:/Users/jnama/machine/Students-grade-prediction-model/your_mlflow_uri/871227263369960388/5f2f4bbbed4342aeb9cc2b0104d02910/artifacts
end_time: 1711028010457
entry_point_name: ''
experiment_id: '871227263369960388'
lifecycle_stage: active
run_id: 5f2f4bbbed4342aeb9cc2b0104d02910
run_name: handsome-horse-94
run_uuid: 5f2f4bbbed4342aeb9cc2b0104d02910
source_name: ''
source_type: 4
source_version: ''
start_time: 1711028010388
status: 3
tags: []
user_id: jnama
